import { DocumentAttachType } from '@/modules/cis/enum/cis.enum';
import { IsNotEmpty, IsEnum, IsOptional } from 'class-validator';

export enum DocumentType {
  ID_CARD_FRONT = 'ID_CARD_FRONT',
  ID_CARD_BACK = 'ID_CARD_BACK',
  ID_CARD_WITH_PERSON = 'ID_CARD_WITH_PERSON',
  COPY_OF_ID_OR_PASSPORT_AUTHORIZED_PERSON = 'COPY_OF_ID_OR_PASSPORT_AUTHORIZED_PERSON',
  COPY_OF_HOUSE_REGISTRATION_AUTHORIZED_PERSON = 'COPY_OF_HOUSE_REGISTRATION_AUTHORIZED_PERSON',
  POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY',
  COPY_OF_ID_OR_PASSPORT_ATTORNEY_GIVER = 'COPY_OF_ID_OR_PASSPORT_ATTORNEY_GIVER',
  COPY_OF_COMPANY_REGISTRATION = 'COPY_OF_COMPANY_REGISTRATION',
  COPY_OF_VAT_REGISTRATION = 'COPY_OF_VAT_REGISTRATION',
  TRADEMARK = 'TRADEMARK',
  PHOTO_OF_COMPANY_OR_PROJECT = 'PHOTO_OF_COMPANY_OR_PROJECT',
  COPY_OF_BANK_ACCOUNT_RECEIVING_PAYMENTS = 'COPY_OF_BANK_ACCOUNT_RECEIVING_PAYMENTS',
  OTHERS = 'OTHERS',
}

export enum DocumentTypeCode {
  ID_CARD_FRONT = '0001',
  ID_CARD_BACK = '0002',
  ID_CARD_WITH_PERSON = '0003',
  COPY_OF_ID_OR_PASSPORT_AUTHORIZED_PERSON = '0004',
  COPY_OF_HOUSE_REGISTRATION_AUTHORIZED_PERSON = '0014',
  POWER_OF_ATTORNEY = '0011',
  COPY_OF_ID_OR_PASSPORT_ATTORNEY_GIVER = '0012',
  COPY_OF_COMPANY_REGISTRATION = '0005',
  COPY_OF_VAT_REGISTRATION = '0006',
  TRADEMARK = '0010',
  PHOTO_OF_COMPANY_OR_PROJECT = '0009',
  COPY_OF_BANK_ACCOUNT_RECEIVING_PAYMENTS = '0008',
  OTHERS = '0013',
}

export class UploadDocumentCisDto {
  @IsEnum(DocumentType)
  @IsOptional()
  documentType: DocumentType;

  @IsEnum(DocumentAttachType)
  @IsNotEmpty()
  attachType: DocumentAttachType;
}
