export enum JuristicTypeValue {
  PERSONAL = 'PERSONAL',
  PUBLIC_LIMITED_COMPANY = 'PUBLIC_LIMITED_COMPANY',
  LIMITED_COMPANY = 'LIMITED_COMPANY',
  LIMITED_PARTNERSHIP = 'LIMITED_PARTNERSHIP',
  GENERAL_PARTNERSHIP = 'GENERAL_PARTNERSHIP',
  OTHER = 'OTHER',
  REGISTERED_INDIVIDUAL = 'REGISTERED_INDIVIDUAL',
}

export enum DocumentType {
  COPY_OF_ID_OR_PASSPORT_AUTHORIZED_PERSON = 'COPY_OF_ID_OR_PASSPORT_AUTHORIZED_PERSON',
  COPY_OF_COMPANY_REGISTRATION = 'COPY_OF_COMPANY_REGISTRATION',
  COPY_OF_VAT_REGISTRATION = 'COPY_OF_VAT_REGISTRATION',
  COPY_OF_FINANCIAL_EVIDENCE = 'COPY_OF_FINANCIAL_EVIDENCE',
  COPY_OF_BANK_ACCOUNT_RECEIVING_PAYMENTS = 'COPY_OF_BANK_ACCOUNT_RECEIVING_PAYMENTS',
  PHOTO_OF_COMPANY_OR_PROJECT = 'PHOTO_OF_COMPANY_OR_PROJECT',
  TRADEMARK = 'TRADEMARK',
  POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY',
  COPY_OF_ID_OR_PASSPORT_ATTORNEY_GIVER = 'COPY_OF_ID_OR_PASSPORT_ATTORNEY_GIVER',
  OTHERS = 'OTHERS',
  COPY_OF_HOUSE_REGISTRATION_AUTHORIZED_PERSON = 'COPY_OF_HOUSE_REGISTRATION_AUTHORIZED_PERSON',
}

export enum OrganizationBranchType {
  HEAD_OFFICE = 'HEAD_OFFICE',
  BRANCH = 'BRANCH',
}

export enum OrgType {
  PERSONAL = 'PERSONAL',
  JURISTIC = 'JURISTIC',
  REGISTERED_INDIVIDUAL = 'REGISTERED_INDIVIDUAL',
}

export const MULTIPLE_ALLOWED_FILE_TYPES = [
  'image/jpeg',
  'image/jpg',
  'image/png',
  'application/pdf',
];

export const MAX_FILE_SIZE = 20 * 1024 * 1024; // 20MB in bytes

export enum DBDStatus {
  ACTIVE = 'ยังดำเนินกิจการอยู่',
  DISSOLVED = 'เลิก',
  IN_LIQUIDATION = 'อยู่ระหว่างชำระบัญชี',
  LIQUIDATED = 'เสร็จการชำระบัญชี',
  STRUCK_OFF = 'ถูกเพิกถอน/ตัดชื่อออกจากทะเบียน',
  SUSPENDED = 'ระงับการดำเนินกิจการชั่วคราว',
  PENDING_REGISTRATION = 'อยู่ระหว่างจดทะเบียน/รออนุมัติ',
  BANKRUPTCY_PROCEEDING = 'อยู่ระหว่างคดีล้มละลาย',
  UNKNOWN = 'UNKNOWN',
}
