export const STEPS = {
  PRODUCT_SELECTION: 'PRODUCT_SELECTION',
  MERCHANT_SELECTION: 'MERCHANT_SELECTION',
  CHECK_RESULTS: 'CHECK_RESULTS',
  ADDABLE_DETAIL: 'ADDABLE_DETAIL',
  DUPLICATED_DETAIL: 'DUPLICATED_DETAIL',
} as const;

export type Step = typeof STEPS[keyof typeof STEPS];
