export enum AddressType {
  OFFICIAL_ADDRESS = 'OFFICIAL_ADDRESS',
  SHIPPING_ADDRESS = 'SHIPPING_ADDRESS',
  CONTACT_ADDRESS = 'CONTACT_ADDRESS',
  AR_ADDRESS = 'AR_ADDRESS',
  DEFAULT = 'DEFAULT',
  KYC_ADDRESS = 'KYC_ADDRESS',
  WORK_SITE_ADDRESS = 'WORK_SITE_ADDRESS',
  DOCUMENT_DELIVERY_ADDRESS = 'DOCUMENT_DELIVERY_ADDRESS',
  WAREHOUSE_ADDRESS = 'WAREHOUSE_ADDRESS',
}
