export enum DocumentType {
  ID_CARD_FRONT = 'ID_CARD_FRONT',
  ID_CARD_BACK = 'ID_CARD_BACK',
  ID_CARD_WITH_PERSON = 'ID_CARD_WITH_PERSON',
  COPY_OF_ID_OR_PASSPORT_AUTHORIZED_PERSON = 'COPY_OF_ID_OR_PASSPORT_AUTHORIZED_PERSON',
  COPY_OF_COMPANY_REGISTRATION = 'COPY_OF_COMPANY_REGISTRATION',
  COPY_OF_VAT_REGISTRATION = 'COPY_OF_VAT_REGISTRATION',
  COPY_OF_FINANCIAL_EVIDENCE = 'COPY_OF_FINANCIAL_EVIDENCE',
  COPY_OF_BANK_ACCOUNT_RECEIVING_PAYMENTS = 'COPY_OF_BANK_ACCOUNT_RECEIVING_PAYMENTS',
  PHOTO_OF_COMPANY_OR_PROJECT = 'PHOTO_OF_COMPANY_OR_PROJECT',
  TRADEMARK = 'TRADEMARK',
  POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY',
  COPY_OF_ID_OR_PASSPORT_ATTORNEY_GIVER = 'COPY_OF_ID_OR_PASSPORT_ATTORNEY_GIVER',
  OTHERS = 'OTHERS',
  COPY_OF_HOUSE_REGISTRATION_AUTHORIZED_PERSON = 'COPY_OF_HOUSE_REGISTRATION_AUTHORIZED_PERSON',
  COMMERCIALLY_REGISTERED = 'COMMERCIALLY_REGISTERED'
}

export const ALLOWED_FILE_TYPES = ['image/jpeg', 'image/jpg', 'image/png'];

export const MAX_FILE_SIZE = 3 * 1024 * 1024; // 3MB in bytes
