worker_processes 1;
 
events {
    worker_connections 1024;
}
 
http {
    include mime.types;
    default_type application/octet-stream;
 
    sendfile on;
    keepalive_timeout 65;
 
    server {
        listen 80;
        server_name  localhost;
        server_tokens  off; # disable the Server nginx header

        # enable gzip
        gzip on;
        gzip_disable "msie6";

        gzip_comp_level 6;
        gzip_min_length 1100;
        gzip_buffers 16 8k;
        gzip_proxied any;
        gzip_types
            text/plain
            text/css
            text/js
            text/xml
            text/javascript
            application/javascript
            application/x-javascript
            application/json
            application/xml
            application/rss+xml
            image/svg+xml;
 
        # Route /storybook to static Storybook
        location ^~ /storybook {
            alias /usr/share/nginx/html/storybook-static;
            index index.html;
            try_files $uri $uri/ /storybook-static/index.html;
        }

        location ^~ /ui-kits {
            alias /usr/share/nginx/html/;
            index ui-kits.html;
            try_files $uri $uri/ ui-kits.html;
        }
 
         # Default location for all other requests
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            # try_files $uri $uri/ =404;
        }
    }
}