# Project Identification
sonar.projectKey=Allkons-Marketplace-API-Customer
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sources=.

# Paths of files to exclude to check coverage
# sonar.coverage.exclusions=**/*.spec.ts,src/main.ts,src/**/*.module.ts,src/**/*.type.ts,src/**/*.dto.ts,src/**/*.entity.ts,src/**/*.document.ts,src/**/*.d.ts,src/common/constants,src/common/decorators,src/common/enums,src/common/entities,src/common/types,src/config/**,

# File inclusions and exclusions
# sonar.inclusions=src/**/*.(ts|js)  # Include all TypeScript and JavaScript files under src directory
# sonar.exclusions=**/*.d.ts  # Exclude definition files

# Set Language
# sonar.language=ts

# Test Report Paths
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=coverage/test-report.xml  # Jest test report in XML format (optional)

# File Extensions
# sonar.typescript.file.suffixes=.ts,.js

# Coverage Settings
# sonar.coverage.exclusions=src/main.ts,src/**/*.module.ts,src/**/*.type.ts,src/**/*.dto.ts,src/**/*.entity.ts,src/**/*.document.ts,src/**/*.d.ts,src/common/**,src/config/**,src/modules/shared/prisma/**
# sonar.coverageReportPaths=coverage/lcov.info

# Map Module Aliases (Similar to moduleNameMapper in Jest)
# sonar.typescript.module.mapper=^@/(.*)$=<rootDir>/src/$1